### PR TITLE
Family snapshot view

### PR DESCRIPTION
**Pull request by bsandoval**
The template shows now real the information of a family with his last snapshot

### CODE REVIEW

**Comment by bsandoval** [comment]
Dear maintainer,
Can you please check the changes? The labels are now in English!

**Comment by rodrigojv** [comment]
@bsandoval I have some files conflicts 😅 :
src/app/families/routes.js
src/app/families/show/view.js
src/app/families/storage.js

Could you please resolve them and push it again?

```
$ git remote -v
origin	https://github.com/rodrigojv/fp-psp-frontend (fetch)
origin	https://github.com/rodrigojv/fp-psp-frontend (push)
upstream	https://github.com/FundacionParaguaya/fp-psp-frontend.git (fetch)
upstream	https://github.com/FundacionParaguaya/fp-psp-frontend.git (push)

$ git fetch upstream
$ git merge upstream/master
```

**Comment by bsandoval** [comment]
Resolved! could you please check it again?

**Comment by bsandoval** [comment]
Resolved! could you please check it again?

**Pull request merged**
