### PR TITLE
Instabug integration - resolve conflicts

### PR DESCRIPTION
**Pull request by IvaKop**

### CODE REVIEW

**Comment by IvaKop** [comment]
@rodrigojv I created a new pull request with no conflicts but I appear to failing a test. 
I tried out the instabug integration on both development and build and it was working perfectly.
Can you help me out?

**Comment by rodrigojv** [comment]
@IvaKop the test is not finding the variable `ibgSdk`. You can try define `ibgSdk` in `tests/globals.js` and then run the test in your local environment `npm run test` to see if it works.

**Comment by IvaKop** [comment]
@rodrigojv Adding the var to tests/globals.js didn't work but I added a check directly in the script tag and it passes the test now :)

**Comment by rodrigojv** [comment]
Fantastic :)

**Pull request merged**
